// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0MDkYK7EYcIeGiooS72W1SPOUjpYqCw',
    appId: '1:251186351407:web:a3d06a7958b00b39b4e5da',
    messagingSenderId: '251186351407',
    projectId: 'greencart-aabe9',
    authDomain: 'greencart-aabe9.firebaseapp.com',
    storageBucket: 'greencart-aabe9.appspot.com',
    measurementId: 'G-C45FZN3CYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTg6q3LchN2Znszu-lpXiLf_4vBGQ_mw',
    appId: '1:251186351407:android:7cb4cd3db4ff3a67b4e5da',
    messagingSenderId: '251186351407',
    projectId: 'greencart-aabe9',
    storageBucket: 'greencart-aabe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB1MkQ6uRaOxnuVburyvshhsqYKRMAEN0',
    appId: '1:251186351407:ios:4e8557ce47450f24b4e5da',
    messagingSenderId: '251186351407',
    projectId: 'greencart-aabe9',
    storageBucket: 'greencart-aabe9.appspot.com',
    androidClientId: '251186351407-0coh49ucfsvsq1btbe8n4c5k5cf4rt99.apps.googleusercontent.com',
    iosClientId: '251186351407-42v8b3drcr78mfq9v2eonnis4kpdko0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB1MkQ6uRaOxnuVburyvshhsqYKRMAEN0',
    appId: '1:251186351407:ios:efd8162c4bb7672db4e5da',
    messagingSenderId: '251186351407',
    projectId: 'greencart-aabe9',
    storageBucket: 'greencart-aabe9.appspot.com',
    androidClientId: '251186351407-0coh49ucfsvsq1btbe8n4c5k5cf4rt99.apps.googleusercontent.com',
    iosClientId: '251186351407-ccockjlsc10kc7h6e3i561bjvni71ror.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenCart.RunnerTests',
  );
}
